import os
import numpy as np
from numpy.linalg import inv
import open3d as o3d
from scipy.spatial import cKDTree
from types import SimpleNamespace
import trimesh
import torch
from transformers import AutoImageProcessor, AutoModelForDepthEstimation
import cv2
import matplotlib.pyplot as plt
from types import SimpleNamespace

from interactive_painting import paint_mask_hd, mask_multiple_images_hd
import da_semantic_masking as dsm
import colorMasks as cm

import random
from pathlib import Path

# ===== COLORIZE_FROM_MASK.PY PSEUDO-CODE OUTLINE =====

#%% Step 1: Establish Script-Wide Variables and Paths
num_classes = 5
SCENE = "Basement"
SCANPOS = "ScanPos001"
project_dir = f"pcml/data/riegl/{SCENE}"
scanpos_dir = f"pcml/data/riegl/{SCENE}/{SCANPOS}"

paths = {
    'data' : os.path.join(scanpos_dir, "DATA"),
    'raw' : os.path.join(scanpos_dir, "CAM/images/raw"),
    'masks' : os.path.join(scanpos_dir, "CAM/images/masks"),
    'matrices' : os.path.join(scanpos_dir, "CAM/matrices"),
    'intrinsics' : f"{project_dir}/intrinsics.dat",
    'pop' : f"{project_dir}/POP.dat",
    'sop' : f"{scanpos_dir}/{SCANPOS}.dat"
}

#%% Step 2: Load Data
def load_pngs_from_folder(folder):
    folder = paths['masks']
    image_paths = sorted([
        p for p in folder.iterdir()
        if p.suffix.lower() == ".png" and not p.stem.endswith("_color")
        ])

    images = []
    valid_paths = []

    for p in image_paths:
        img = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
        if img is None:
            print(f"Warning: could not read {p}")
            continue
        images.append(img)
        valid_paths.append(p)
    return images, valid_paths

#%% Step 3: Transformations

def glcs_to_socs(point_cloud, PRCS_GLCS, SOCS_PRCS, point_cloud_socs_path):
    '''
    Transform a point cloud from a global reference frame (GLCS) to the scanner's reference frame (SOCS)

    Inputs:
        point_cloud : The point cloud from a given scan postion in the global reference frame with X, Y, Z, Classification, and Point ID as attributes. LAZ file?
        PRCS_GLCS : The transformation matrix transforming points from the projects reference frame to the global reference frame. Called POP by Riegl. *.dat or *.4x4
        SOCS_PRCS : The transformation matrix transforming points from the scanner's reference frame to the project's reference frame. Called SOP by Riegl. *.dat or *.4x4
        point_cloud_socs : The path and filename to which the SOCS-centered point cloud will be written

    Outputs:
        A point cloud at Path(point_cloud_socs) in the scanner's refernce frame with X, Y, Z, Classification, and Point ID as attributes. 
    '''

    pc = np.load_function(point_cloud) # this should be a tensor built by a yet unknown to me loading function?
    
    print(f"Transforming {pc} from GLCS to SOCS")


    # Define each intermediate point cloud
    pc_socs = o3d.geometry.PointCloud()
    
    # Define each transformation matrix
    matrices = SimpleNamespace(
        POP = np.loadtext(paths['pop'], delimiter=','),
        SOP = np.loadtext(paths['sop'], delimiter=','),
    )

    # transform each point into the camera's reference frame
    for i in range(len(pc)):
        pc_socs[i] = inv(matrices.SOP) @ inv(matrices.POP) @ pc[i] # glcs > prcs > SOCS
    
    np.save_function(pc_socs, Path(point_cloud_socs_path)) # save the transformed point cloud using a yet unknown to me saving function?


def classify_point_cloud(point_cloud_socs, images, mask_intrinsics, CMCS_SOCS, Z_ROTATION, output_path):
    '''
    A. For each image:
        1) Transform the points into the camera's reference frame
        2) Project the points onto the image
        3) Read the value of the mask pixel and store that in it's own field
        4) Reproject the point cloud back into the scanner's reference frame.
        5) Transform the points back into the global reference frame.
    
    B. After process A, for each point in the point cloud:
        1) Compare all of the values stored in the "extra bytes" from the mask values.
        2) Assign the most common value to Classification. If there's a tie, set Classification to 255.
        3) Once a value has been set for Classification for all points, return to the set of points with Classification == 255:
            3.1) Rank the classification values of the point's 19-point neighborhood.
            3.2) Set that point's classification value to the most common value in it's neightborhood. If there's still a tie weight the neighborhood points by the inverse of their euclidean distance from x[i] and chose the classification with the highest score. Set the classification value for x[i] to the winning classification value.
    
    C. Save the point cloud as a LAZ file.

    Inputs:
        - point_cloud_socs: path to the point cloud in the scanner's reference frame generated by glcs_to_socs()
        - mask_images: path to the mask images generated by painting.
        - mask_intrinsics: the camera intrinsics file to apply to the masks (.txt or .csv)
        - CMCS_SOCS: the transformation matrix transforming points from the camera's reference frame to the scanner's reference frame
        - Z-ROTATION: path to the location of the transformation matrices describing the rotation around the scanner's z-axis that happens when the scanner rotates and the photograph is taken.
        - output_path: path where the final, classified point cloud should be written.

    Outputs:
        - A point cloud at Path(output_path) containing all the same attributes as the origical point cloud but also containing a classification value.
    '''

    pc = o3d.t.io.read_point_cloud(Path(point_cloud_socs)) # read-in the SOCS point cloud

    N = pc.point.positions.shape[0] # number of points
    device = pc.point.positions.device # is the point cloud on CPU or GPU

    pc_cmcs = o3d.t.geometry.PointCloud(pc) # clone pc to be transformed later

    pc_cmcs.point.px_vals = o3d.core.Tensor( 
    # (N x len(images)) tensor storing 1 px val per point per image
        np.full((N, len(images)), -1, dtype=np.int32),
        dtype = o3d.core.int32,
        device = device
    )
    
    pc_cmcs.point.class_votes = o3d.core.Tensor( 
    # (N x num_classes) tensor storing the counts of each px_val for each point
        np.full((N, num_classes), 0, dtype=np.int32),
        dtype = o3d.core.int32,
        device = device
    )

    camera_intrinsics = paths['intrinsics']

    fx, fy = camera_intrinsics[0, 0], camera_intrinsics[1, 1]
    cx, cy = camera_intrinsics[0, 2], camera_intrinsics[1, 2]
    dx = 0.00000376
    dy = 0.00000376
    nx = 9504
    ny = 6336
    ax = (fx * dx) / nx
    ay = (fy * dy) / ny
    
    '''K = np.array([(fx*dx)/nx, 0, cx, 0],
                 [0, (fy*dy)/ny, cy, 0],
                 [0, 0, 1, 0])'''

    for j, img in enumerate(images):
        # for each image, transform pc into the camera's frame of reference, then project the points onto the image
        z_rot = np.loadtxt(Path(f"{paths['matrices']}/{images[img]}.dat"), delimiter=',') # the z-rotation matrix for img
        MM = np.loadtext(Path(f"{paths['matrices']}/mounting.dat") , delimiter=',') # the mounting matrix for img

        pc_cmcs = o3d.geometry.PointCloud(pc).Transform(z_rot).Transform(MM) # Transform the point cloud into the camera's reference frame

        pts = pc_cmcs.points.positions.numpy() # make the point cloud into something through which I can loop.

        for i, (x, y, z) in enumerate(pts): # loop through each point 
            n = ((ax * x) / z) + cx # find the x-pixel the point projects to
            m = ((ay * y) / z) + cy # find the y-pizel the point projects to

            if not np.isnan(img[n,m]): # if there is a pixel value associated with the point
                pc_cmcs.point.px_vals[i,j] = img[n,m] # push the pixel value to px_vals for each point
                    
    for p, row in enumerate(pts): # for every point
        for c in range(num_classes): # and for each class
            pc_cmcs.point.class_votes[p,c] = np.count_nonzero(row == c) # set the value of class_votes[p,c] to the number of occurances of that class

    for p, row in enumerate(pc_cmcs.point.class_votes): # for each point
        pc_cmcs.point.classification[p] = pc_cmcs.point.class_votes[p,np.int32(np.argmax(row))] # set the classification value to the value of the column index with the most votes. In the case where there is a tie the smaller index gets chosen by this. I had an idea of using kNN as a tie-breaker but that might be too complex for now. 

    pc_cmcs.point.classification = o3d.core.Tensor(
        # (N, ) tensor storing the derived classification value for each point
        np.argmax(row) for row in pc_cmcs.point.class_votes,
        dtype = o3d.core.int32,
        device = device
        )
    

     