import os
import numpy as np
from numpy.linalg import inv
import open3d as o3d
from scipy.spatial import cKDTree
from types import SimpleNamespace
import trimesh
import torch
from transformers import AutoImageProcessor, AutoModelForDepthEstimation
import cv2
import matplotlib.pyplot as plt
from types import SimpleNamespace

from interactive_painting import paint_mask_hd, mask_multiple_images_hd
import da_semantic_masking as dsm
import colorMasks as cm

import random
from pathlib import Path

# ===== COLORIZE_FROM_MASK.PY PSEUDO-CODE OUTLINE =====

#%% Step 1: Establish Script-Wide Paths
SCENE = "Basement"
SCANPOS = "ScanPos001"
project_dir = f"pcml/data/riegl/{SCENE}"
scanpos_dir = f"pcml/data/riegl/{SCENE}/{SCANPOS}"

paths = {
    'data' : os.path.join(scanpos_dir, "DATA"),
    'raw' : os.path.join(scanpos_dir, "CAM/images/raw"),
    'masks' : os.path.join(scanpos_dir, "CAM/images/masks"),
    'matrices' : os.path.join(scanpos_dir, "CAM/matrices"),
    'intrinsics' : f"{project_dir}/intrinsics.dat",
    'pop' : f"{project_dir}/POP.dat",
    'sop' : f"{scanpos_dir}/{SCANPOS}.dat"
}

#%% Step 2: Load Data
def load_pngs_from_folder(folder):
    folder = paths['masks']
    image_paths = sorted([
        p for p in folder.iterdir()
        if p.suffix.lower() == ".png" and not p.stem.endswith("_color")
        ])

    images = []
    valid_paths = []

    for p in image_paths:
        img = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
        if img is None:
            print(f"Warning: could not read {p}")
            continue
        images.append(img)
        valid_paths.append(p)
    return images, valid_paths

#%% Step 3: Transformations

def glcs_to_socs(point_cloud, PRCS_GLCS, SOCS_PRCS, point_cloud_socs_path):
    '''
    Transform a point cloud from a global reference frame (GLCS) to the scanner's reference frame (SOCS)

    Inputs:
        point_cloud : The point cloud from a given scan postion in the global reference frame with X, Y, Z, Classification, and Point ID as attributes. LAZ file?
        PRCS_GLCS : The transformation matrix transforming points from the projects reference frame to the global reference frame. Called POP by Riegl. *.dat or *.4x4
        SOCS_PRCS : The transformation matrix transforming points from the scanner's reference frame to the project's reference frame. Called SOP by Riegl. *.dat or *.4x4
        point_cloud_socs : The path and filename to which the SOCS-centered point cloud will be written

    Outputs:
        A point cloud at Path(point_cloud_socs) in the scanner's refernce frame with X, Y, Z, Classification, and Point ID as attributes. 
    '''

    pc = np.load_function(point_cloud) # this should be a tensor built by a yet unknown to me loading function?
    
    print(f"Transforming {pc} from GLCS to SOCS")


    # Define each intermediate point cloud
    pc_socs = o3d.geometry.PointCloud()
    
    # Define each transformation matrix
    matrices = SimpleNamespace(
        POP = np.loadtext(paths['pop'], delimiter=','),
        SOP = np.loadtext(paths['sop'], delimiter=','),
    )

    # transform each point into the camera's reference frame
    for i in range(len(pc)):
        pc_socs[i] = inv(matrices.SOP) @ inv(matrices.POP) @ pc[i] # glcs > prcs > SOCS
    
    np.save_function(pc_socs, Path(point_cloud_socs_path)) # save the transformed point cloud using a yet unknown to me saving function?


def colorize_point_cloud(point_cloud_socs, images, mask_intrinsics, CMCS_SOCS, Z_ROTATION, output_path):
    '''
    A. For each image:
        1) Transform the points into the camera's reference frame
        2) Project the points onto the image
        3) Read the value of the mask pixel and store that in it's own field
        4) Reproject the point cloud back into the scanner's reference frame.
        5) Transform the points back into the global reference frame.
    
    B. After process A, for each point in the point cloud:
        1) Compare all of the values stored in the "extra bytes" from the mask values.
        2) Assign the most common value to Classification. If there's a tie, set Classification to 255.
        3) Once a value has been set for Classification for all points, return to the set of points with Classification == 255:
            3.1) Rank the classification values of the point's 19-point neighborhood.
            3.2) Set that point's classification value to the most common value in it's neightborhood. If there's still a tie weight the neighborhood points by the inverse of their euclidean distance from x[i] and chose the classification with the highest score. Set the classification value for x[i] to the winning classification value.
    
    C. Save the point cloud as a LAZ file.

    Inputs:
        - point_cloud_socs: path to the point cloud in the scanner's reference frame generated by glcs_to_socs()
        - mask_images: path to the mask images generated by painting.
        - mask_intrinsics: the camera intrinsics file to apply to the masks (.txt or .csv)
        - CMCS_SOCS: the transformation matrix transforming points from the camera's reference frame to the scanner's reference frame
        - Z-ROTATION: path to the location of the transformation matrices describing the rotation around the scanner's z-axis that happens when the scanner rotates and the photograph is taken.
        - output_path: path where the final, classified point cloud should be written.

    Outputs:
        - A point cloud at Path(output_path) containing all the same attributes as the origical point cloud but also containing a classification value.
    '''

    pc = np.load_function(Path(point_cloud_socs)) # a tensor built by a yet uknown to me loading funtion
    pc_cmcs = o3d.geometry.PointCloud()
    camera_intrinsics = paths['intrinsics']
    
    fx, fy = camera_intrinsics[0, 0], camera_intrinsics[1, 1]
    cx, cy = camera_intrinsics[0, 2], camera_intrinsics[1, 2]
    dx = 0.00000376
    dy = 0.00000376
    nx = 9504
    ny = 6336

    K = np.array([(fx*dx)/nx, 0, cx, 0],
                 [0, (fy*dy)/ny, cy, 0],
                 [0, 0, 1, 0])



    # 3-D Pythagoras re-arranges to solve for z
    z = depth_image / np.sqrt(1. + x_over_z**2 + y_over_z**2)
    x = x_over_z * z

    for img in range(len(images)):
        # for each image, transform pc into the camera's frame of reference, then project the points onto the image
        z_rot = np.loadtxt(Path(f"{paths['matrices']}/{images[img]}.dat"), delimiter=',') # the z-rotation matrix for img
        MM = np.loadtext(Path(f"{paths['matrices']}/mounting.dat") , delimiter=',') # the mounting matrix for img
        
        width, height = images[img].shape
        
        pc_cmcs = o3d.geometry.PointCloud(pc).Transform(z_rot).Transform(MM)